# Основные настройки форматирования
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
objectWrap: collapse

# Плагины
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - prettier-plugin-jsdoc

# Конфигурация сортировки импортов
importOrder:
  - '^[a-zA-Z]'
  - '^[@./]'
importOrderSeparation: true
importOrderSortSpecifiers: true

# Настройки для JSDoc
jsdocSpaces: 1
jsdocDescriptionWithDot: false
jsdocDescriptionTag: false
