ignoredBuiltDependencies:
  - esbuild

overrides:
  squidlet-lib: link:../../../../home/ivan/.local/share/pnpm/global/5/node_modules/squidlet-lib
  squildlet-lib: link:../../../../home/ivan/.local/share/pnpm/global/5/node_modules/squildlet-lib
