# when using the default proxy server port
local_backend: true
backend:
  name: git-gateway

publish_mode: editorial_workflow
site_url: https://antifem-move.org
media_folder: src/public/media
public_folder: /media
locale: ru
# media_library:
#   max_file_size: 512000
#   folder_support: true
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en
  enforce_required_non_default: false
collections:
  - name: doc
    label: Docs
    label_singular: Doc
    description: All the docs
    i18n: true
    # i18n:
    #   structure: multiple_files
    folder: "src"
    # folder: "doc"
    # path: "{{dirname}}/doc"
    # path: "doc/{{slug}}"
    # preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    # slug: "doc-{{slug}}"
    create: true
    # filter:
    #   pattern: "^index"
    filter:
      pattern: "^doc"
    # filter:
    #   field: editLink
    #   value: "false"
    # nested:
    #   depth: 100 # max depth to show in the collection tree
    #   summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
    #   # adding a path object allows editing the path of entries
    #   # moving an existing entry will move the entire sub tree of the entry to the new location
    #   path: { widget: string, index_file: "index" }
    summary: "{{dirname}}/{{filename}} {{commit_date | date('yyyy-MM-dd')}} {{title}}"
    # sortable_fields:
    #   fields: ["commit_date", "title", "commit_author"]
    #   default:
    #     field: commit_date
    #     direction: Descending
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        i18n: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true
        show_raw: true
  # - name: sidebar
  #   label: "Sidebar"
  #   i18n:
  #     structure: multiple_files
  #   delete: false
  #   extension: yaml
  #   format: yaml
  #   folder: "src/.vitepress/locales/menu"
  #   fields:
  #     - label: "Title"
  #       name: "title"
  #       widget: "string"
  #     - label: "Body"
  #       name: "body"
  #       widget: "code"
  #       default_language: yaml
  #       i18n: true
  #
  # - name: "ru-doc"
  #   label: "RU doc"
  #   folder: "src/ru/doc"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - label: "Title"
  #       name: "title"
  #       widget: "string"
  #       i18n: true
  #     - label: "Description"
  #       name: "description"
  #       widget: "string"
  #       required: false
  #       i18n: true
  #     - label: "Body"
  #       name: "body"
  #       widget: "markdown"
  #       show_raw: true
  #       i18n: true
  #     #- { label: "Featured Image", name: "thumbnail", widget: "image" }
  # - name: menu
  #   label: Menu
  #   folder: src/.vitepress/locales/menu
  #   create: false
  #   delete: false
  #   extension: yaml
  #   format: yaml
  #   editor:
  #     preview: false
  #   fields:
  #     - label: Body
  #       name: body
  #       widget: code
