i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en

backend:
  name: github
  repo: '...'
  use_graphql: true
  # skip_ci: true
  # site_domain: 5ab4c367-3592-4361-a4b8-ccd46514c967

site_url: https://blog....
media_folder: /src/public/media
public_folder: /media

media_library:
  name: default
  config:
    slugify_filename: true
    # 10 mb
    max_file_size: 10240000
    transformations:
      raster_image:
        format: webp
        quality: 65 # default: 85
        width: 1920 # default: original size
        height: 1920 # default: original size
      svg:
        optimize: true

slug:
  encoding: ascii
  clean_accents: true

output:
  omit_empty_optional_fields: true

collections:
  - name: posts
    label: Posts
    label_singular: Post
    description: All the posts
    i18n: true
    folder: 'src'
    path: 'post/{{slug}}'
    slug: "{{date | date('YYYY')}}-{{slug}}"
    preview_path: '/{{locale}}/post/{{slug}}'
    media_folder: /src/public/media
    public_folder: /media
    create: true
    summary: '{{title}} | {{commit_date}} | {{commit_author}}'
    sortable_fields:
      fields: ['date', 'title', 'authorId']
      default:
        field: date
        direction: descending # default: ascending
    view_groups:
      default: by-year
      groups:
        - name: by-year
          label: Year
          field: date
          pattern: \d{4}
        - name: by-author
          label: Author
          field: authorId
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        preview: false
        i18n: true
      - label: Publication date (your locale)
        name: date
        widget: datetime
        format: 'YYYY-MM-DDTHH:mmZ'
        preview: false
        i18n: duplicate
      - label: 'Description (please do less than 500 chars)'
        name: 'description'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Replace text for preview for articles and list items'
        name: 'previewText'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Use description as a preview (if not set previewText)'
        name: 'descrAsPreview'
        widget: 'boolean'
        default: true
        required: false
        preview: false
        i18n: duplicate
      - label: "Canonical URL ('self' means self-canonical)"
        name: 'canonical'
        widget: 'string'
        default: 'self'
        required: false
        preview: false
        i18n: true
      - label: 'JSON-LD in yaml format. Add some fields to the generated JSON-LD or make full JSON-LD'
        name: 'jsonLd'
        widget: code
        required: false
        preview: false
        i18n: true
        output_code_only: true
        default_language: yaml
        allow_language_selection: false
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        required: false
        i18n: duplicate
      - label: 'Description of cover image'
        name: 'coverDescr'
        widget: 'string'
        required: false
        i18n: true
      - label: 'Alt of cover image'
        name: 'coverAlt'
        widget: 'string'
        required: false
        i18n: true
      - label: 'commentUrl'
        name: 'commentUrl'
        widget: 'string'
        required: false
        preview: false
        i18n: true
      - name: authorId
        label: Author
        widget: select
        options: ['ivan-k']
        required: false
        preview: false
        i18n: duplicate
      - label: 'Url to video'
        name: 'videoLink'
        widget: 'string'
        required: false
        preview: false
        i18n: true
      - label: 'Language of the video (set only if not equal to the page lang)'
        name: 'videoLinkLang'
        widget: select
        options: ['', 'RU', 'EN']
        default: ''
        required: false
        preview: false
        i18n: true
      - label: 'Podcast URLs'
        name: 'podcasts'
        preview: false
        required: false
        i18n: true
        widget: 'object'
        fields:
          - label: 'castbox'
            name: 'castbox'
            widget: 'string'
            required: false
            i18n: true
          - label: 'soundstream'
            name: 'soundstream'
            widget: 'string'
            required: false
            i18n: true
          - label: 'spotify'
            name: 'spotify'
            widget: 'string'
            required: false
            i18n: true
          - label: 'vk'
            name: 'vk'
            widget: 'string'
            required: false
            i18n: true
          - label: 'yandexmusic'
            name: 'yandexmusic'
            widget: 'string'
            required: false
            i18n: true
          # - { label: "site", name: "site", widget: "string", required: false, i18n: true }
          # - { label: "deezer", name: "deezer", widget: "string", required: false, i18n: true }
          # - { label: "pocketcasts", name: "pocketcasts", widget: "string", required: false, i18n: true }
          # - { label: "applepodcasts", name: "applepodcasts", widget: "string", required: false, i18n: true }
          # - { label: "overcast", name: "overcast", widget: "string", required: false, i18n: true }
          # - { label: "zvuk", name: "zvuk", widget: "string", required: false, i18n: true }
          # - { label: "podcastaddiction", name: "podcastaddiction", widget: "string", required: false, i18n: true }
      - name: tags
        label: Tags
        widget: relation
        collection: _singletons
        file: tags
        required: false
        preview: false
        root: true
        value_field: tags.*.name
        multiple: true
        i18n: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        i18n: true

singletons:
  - name: tags
    label: Tags
    label_singular: Tag
    file: 'src/site/tags.{{locale}}.yaml'
    i18n: true
    editor:
      preview: false
    fields:
      - name: 'tags'
        widget: 'list'
        allow_add: true
        i18n: true
        root: true
        fields:
          - name: 'name'
            label: 'Name'
            widget: string
            i18n: true
  - name: site
    label: Site translations
    file: 'src/site/site.{{locale}}.yaml'
    i18n: true
    editor:
      preview: false
    fields:
      - label: 'Body'
        name: 'body'
        i18n: true
        widget: code
        output_code_only: true
        default_language: yaml
        allow_language_selection: false
  - name: aboutblog
    label: About blog
    file: 'src/{{locale}}/page/about-blog.md'
    preview_path: '/{{locale}}/page/{{slug}}'
    i18n: true
    fields:
      - label: 'Description'
        name: 'description'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        i18n: true
  - name: index
    label: Index
    file: 'src/{{locale}}/index.md'
    preview_path: '/{{locale}}'
    i18n: true
    editor:
      preview: false
    fields:
      - label: 'Body'
        name: 'body'
        i18n: true
        widget: code
        output_code_only: true
