backend:
  name: github
  repo: '...'
  use_graphql: true

site_url: https://blog....
media_folder: src/public/media
public_folder: /media
# media_library:
#   name: default
#   config:
#     max_file_size: 512000
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en
  enforce_required_non_default: false
  # save_all_locales: false
collections:
  - name: posts
    label: Posts
    label_singular: Post
    description: All the posts
    i18n: true
    folder: 'src'
    path: 'post/{{slug}}'
    slug: "{{date | date('YYYY')}}-{{slug}}"
    preview_path: '{{locale}}/post/{{slug}}'
    create: true
    summary: '{{title}} | {{commit_date}} | {{commit_author}} | {{filename}}.md'
    sortable_fields: ['date', 'title', 'authorId']
    # media_folder: src/public/media/{{slug}}
    # public_folder: /media/{{slug}}
    # view_groups:
    #   default: by-year
    #   groups:
    #     - name: by-year
    #       label: Year
    #       field: pubDate
    #       pattern: \d{4}
    #     - name: by-author
    #       label: Author
    #       field: authorId
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        preview: false
        i18n: true
      - label: Publication date (your locale)
        name: date
        widget: datetime
        format: 'yyyy-MM-DDTHH:mmZ'
        preview: false
        i18n: duplicate
      - label: 'Description'
        name: 'description'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Replace text for preview for articles and list items'
        name: 'previewText'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Use description as a preview (if not set previewText)'
        name: 'descrAsPreview'
        widget: 'boolean'
        default: true
        required: false
        preview: false
        i18n: duplicate
      - label: "Canonical URL ('self' means self-canonical)"
        name: 'canonical'
        widget: 'string'
        default: 'self'
        required: false
        preview: false
        i18n: true
      - label: 'JSON-LD in yaml format. Add some fields to the generated JSON-LD or make full JSON-LD'
        name: 'jsonLd'
        widget: 'text'
        required: false
        preview: false
        i18n: true
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
        # media_folder: src/public/media/{{slug}}
        # public_folder: /media/{{slug}}
        # choose_url: true
        required: false
        i18n: true
      - label: 'Description of cover image'
        name: 'coverDescr'
        widget: 'string'
        required: false
        i18n: true
      - label: 'Alt of cover image'
        name: 'coverAlt'
        widget: 'string'
        required: false
        i18n: true
      - label: 'commentUrl'
        name: 'commentUrl'
        widget: 'string'
        required: false
        preview: false
        i18n: true
      - label: 'Url to video'
        name: 'videoLink'
        widget: 'string'
        required: false
        preview: false
        i18n: true
      - label: 'Language of the video (set only if not equal to the page lang)'
        name: 'videoLinkLang'
        widget: select
        options: ['', 'RU', 'EN']
        default: ''
        required: false
        preview: false
        i18n: true
      - label: 'Podcast URLs'
        name: 'podcasts'
        preview: false
        required: false
        i18n: true
        widget: 'object'
        fields:
          - label: 'castbox'
            name: 'castbox'
            widget: 'string'
            required: false
            i18n: true
          - label: 'soundstream'
            name: 'soundstream'
            widget: 'string'
            required: false
            i18n: true
          - label: 'spotify'
            name: 'spotify'
            widget: 'string'
            required: false
            i18n: true
          - label: 'vk'
            name: 'vk'
            widget: 'string'
            required: false
            i18n: true
          - label: 'yandexmusic'
            name: 'yandexmusic'
            widget: 'string'
            required: false
            i18n: true
          # - { label: "site", name: "site", widget: "string", required: false, i18n: true }
          # - { label: "deezer", name: "deezer", widget: "string", required: false, i18n: true }
          # - { label: "pocketcasts", name: "pocketcasts", widget: "string", required: false, i18n: true }
          # - { label: "applepodcasts", name: "applepodcasts", widget: "string", required: false, i18n: true }
          # - { label: "overcast", name: "overcast", widget: "string", required: false, i18n: true }
          # - { label: "zvuk", name: "zvuk", widget: "string", required: false, i18n: true }
          # - { label: "podcastaddiction", name: "podcastaddiction", widget: "string", required: false, i18n: true }
      - label: 'Language of podcast (set only if not equal to the page lang)'
        name: 'podcastLang'
        widget: select
        options: ['', 'RU', 'EN']
        default: ''
        required: false
        preview: false
        i18n: true
      - name: authorId
        label: Author
        widget: select
        options: ['ivan-k']
        required: false
        preview: false
        i18n: duplicate
      - name: tags
        label: Tags
        widget: relation
        collection: files
        file: tags
        required: false
        preview: false
        value_field: tags.*.name
        # search_fields: ["tags.*.name"]
        multiple: true
        i18n: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        i18n: true
  - name: files
    label: 'Files'
    i18n: true
    files:
      - name: tags
        label: Tags
        label_singular: Tag
        extension: yaml
        format: yaml
        file: 'src/site/tags.{{locale}}.yaml'
        i18n: true
        fields:
          - name: 'tags'
            widget: 'list'
            allow_add: true
            i18n: true
            fields:
              - name: 'name'
                label: 'Name'
                widget: string
                i18n: true
      - name: site
        label: Site translations
        extension: yaml
        format: yaml
        file: 'src/site/site.{{locale}}.yaml'
        i18n: true
        fields:
          - name: 'title'
            widget: 'hidden'
            default: Sidebar
            i18n: duplicate
          - label: 'Body'
            name: 'body'
            widget: 'text'
            # default_language: yaml
            i18n: true
      - name: aboutblog
        label: About blog
        file: 'src/{{locale}}/page/about-blog.md'
        preview_path: '{{locale}}/page/{{slug}}'
        i18n: true
        fields:
          - label: 'Description'
            name: 'description'
            widget: 'text'
            required: false
            preview: false
            i18n: true
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
            i18n: true
      - name: index
        label: Index
        file: 'src/{{locale}}/index.md'
        preview_path: '{{locale}}'
        i18n: true
        fields:
          - label: 'Body'
            name: 'body'
            widget: 'text'
            i18n: true
